use bevy::prelude::*;
use serde::{Deserialize, Serialize};

const DEFAULT_SKIN_DESCRIPTOR_PATH: &str = "assets/skins/default/skin.ron";
const BUILTIN_DEFAULT_SKIN: &str = r#"(
    name: "dtxpt default",
    version: 1,
    judgement_font: "system-cjk",
    lane_style: "procedural-flat",
    notes: "Procedural default skin: lane colors, receptors, hit bursts, HUD, and menu theme are generated by dtxpt when bitmap assets are absent.",
)"#;

#[derive(Resource, Debug, Clone, PartialEq, Eq)]
pub struct ActiveSkin {
    pub descriptor: SkinDescriptor,
    pub source: SkinSource,
}

impl FromWorld for ActiveSkin {
    fn from_world(_world: &mut World) -> Self {
        load_default_skin()
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SkinDescriptor {
    pub name: String,
    pub version: u32,
    pub judgement_font: String,
    pub lane_style: String,
    pub notes: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SkinSource {
    AssetDescriptor,
    BuiltinFallback,
}

fn load_default_skin() -> ActiveSkin {
    match std::fs::read_to_string(DEFAULT_SKIN_DESCRIPTOR_PATH)
        .ok()
        .and_then(|text| parse_skin_descriptor(&text).ok())
    {
        Some(descriptor) => {
            info!("loaded default skin descriptor from {DEFAULT_SKIN_DESCRIPTOR_PATH}");
            ActiveSkin {
                descriptor,
                source: SkinSource::AssetDescriptor,
            }
        }
        None => {
            warn!("default skin descriptor missing; using built-in procedural skin");
            ActiveSkin {
                descriptor: parse_skin_descriptor(BUILTIN_DEFAULT_SKIN)
                    .expect("built-in skin descriptor is valid"),
                source: SkinSource::BuiltinFallback,
            }
        }
    }
}

fn parse_skin_descriptor(text: &str) -> Result<SkinDescriptor, ron::error::SpannedError> {
    ron::de::from_str(text)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn builtin_default_skin_descriptor_parses() {
        let skin = parse_skin_descriptor(BUILTIN_DEFAULT_SKIN).unwrap();
        assert_eq!(skin.name, "dtxpt default");
        assert_eq!(skin.version, 1);
        assert_eq!(skin.judgement_font, "system-cjk");
        assert_eq!(skin.lane_style, "procedural-flat");
    }

    #[test]
    fn repository_default_skin_descriptor_parses_when_present() {
        let text = std::fs::read_to_string(DEFAULT_SKIN_DESCRIPTOR_PATH)
            .expect("default skin descriptor should ship with the repo");
        let skin = parse_skin_descriptor(&text).unwrap();
        assert_eq!(skin.name, "dtxpt default");
        assert_eq!(skin.version, 1);
    }
}
